baseURL = 'https://teeta86.github.io/lalitasegal.github.io/'
languageCode = 'en-us'
title = 'Lalita Segal'
theme = 'ananke'
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
[markup.goldmark.renderer]
  unsafe = true    
